### ISSUE TITLE
Rectangle box in captcha images

### ISSUE THREAD

**Issue by newmangreen** [mewebstudio/java-captcha-generator#4]
Hi,

Sometimes captcha generator produces rectangle for some characters. It is not specific with a character, it changes and other character is painted like rectangle.

I captured 2 capcthas with problematic images;
**UFA74** (First character)
![unrecognized character](https://github.com/mewebstudio/java-captcha-generator/assets/26571935/7a7be76b-91f9-40d5-af38-57f843aa4832)

**wmqyE** (Second and third character)
![unrecognized character 2](https://github.com/mewebstudio/java-captcha-generator/assets/26571935/51452ddf-f0c9-4031-848e-8fff0dc50679)

**Comment by mewebstudio** [comment]
Hi,

The reason for this problem is that some fonts on your system are not supported. Try using a different font for the solution.
[https://github.com/mewebstudio/java-captcha-generator?tab=readme-ov-file#how-to-use](https://github.com/mewebstudio/java-captcha-generator?tab=readme-ov-file#how-to-use)

**Comment by newmangreen** [comment]
Thank you but I fixed the problem at my local copy by checking render support of font. 
`font.canDisplay(ch)`
If you want to include it to your repo, I attached my fix. I checked display capability of system fonts and 56 of total 617 can't display 'a' character. Using system fonts provide much more variability to the captcha image. 
[Captcha.java.txt](https://github.com/mewebstudio/java-captcha-generator/files/14720672/Captcha.java.txt)

**Comment by mewebstudio** [comment]
@newmangreen
Thanks, I will consider it for the next version.

**Comment by kasimselimhanbaltas** [comment]
> Thank you but I fixed the problem at my local copy by checking render support of font. `font.canDisplay(ch)` If you want to include it to your repo, I attached my fix. I checked display capability of system fonts and 56 of total 617 can't display 'a' character. Using system fonts provide much more variability to the captcha image. [Captcha.java.txt](https://github.com/mewebstudio/java-captcha-generator/files/14720672/Captcha.java.txt)

I had the same issue. Thanks to you, I just overrided the Captcha class and everything works fine!
