### ISSUE TITLE
Sometimes a letter is not rendered correctly, but is just shown as a square on the image 

### ISSUE THREAD

**Issue by Jezzper** [mewebstudio/java-captcha-generator#6]
Sometimes a letter is not rendered correctly, but is just shown as a square on the image 

![saved89](https://github.com/mewebstudio/java-captcha-generator/assets/34474332/94078754-6555-4afe-8de2-5017a153f220)

**Comment by arturmlodzinski** [comment]
I have the same problem

**Comment by mewebstudio** [comment]
@Jezzper, @arturmlodzinski 

https://github.com/mewebstudio/java-captcha-generator/issues/4#issuecomment-2009978580
